name: Deploy to Cloud Run

on:
  pull_request:
    branches: [master]
    types: closed

  push: 
    branches:
      - master

  workflow_dispatch:


env:
  SERVICE_NAME: 'csv-diff-agent'
  IMAGE_NAME: 'csv-diff-agent'
  APP_NAME: 'csv_diff_agent'
  REGISTRY: 'asia-southeast1-docker.pkg.dev'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.TF_SA_KEY }}'
      

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: login to google artifacts registry
      run: gcloud auth configure-docker ${{ env.REGISTRY }}


    - name: set image name and tag
      run: echo "RELEASE=${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> "$GITHUB_ENV"

    
    - name: build dockerfile
      run: docker build -t "$RELEASE" .
      
    - name: tag latest
      run: docker tag "$RELEASE" "${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/${{ env.IMAGE_NAME }}:latest"

    - name: push hash tag
      run: docker push "$RELEASE"

    - name: push latest tag
      run: docker push "${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT }}/cloud-run-source-deploy/${{ env.IMAGE_NAME }}:latest"

    - name: deploy cloud run 
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
        --image "$RELEASE" \
        --project=${{ secrets.GCP_PROJECT }} \
        --region=${{ secrets.GCP_REGION }} \
        --memory=1Gi \
        --min-instances=0 \
        --max-instances=5 \
        --set-env-vars="GOOGLE_GENAI_USE_VERTEXAI"=1 \
        --set-env-vars="GOOGLE_CLOUD_PROJECT"=${{ secrets.GCP_PROJECT }} \
        --set-env-vars="GOOGLE_CLOUD_LOCATION"="global" \
        --set-env-vars="GEMINI_MODEL"="gemini-2.5-pro-preview-05-06"
